### PR TITLE
Add meson compilation support

### PR DESCRIPTION
**Pull request by zhuyaliang**
## test
```
meson setup _build --prefix=/usr

ninja -C _build

meson install -C _build
```

### CODE REVIEW

**Review by lukefromdc — COMMENTED** [review]
The macros got installed to /usr/aclocal instead of /usr/share/aclocal with the result that they were not found in attempting to build another MATE package. While they can be moved in configuration the default needs to work

**Comment by zhuyaliang** [comment]
@lukefromdc Fixed

**Comment by lukefromdc** [comment]
Just retested:
Although macros and the .omf files were now installed to the same place Autotools would install them an attempt to configure another mate package again failed with

`You need to install mate-common from the MATE Git`

In addition, everything in docs was not installed at all and manpage files were not gzipped

**Comment by zhuyaliang** [comment]
> everything in docs was not installed at all

What doc files are missing?

>manpage files were not gzipped

manpage is compressed build packaging [rpm](https://github.com/rpm-software-management/rpm/blob/master/scripts/brp-compress#L16)

>You need to install mate-common from the MATE Git

Fixed

**Comment by lukefromdc** [comment]
Still no /usr/share/docs/mate-common showing up, the whole directory is missing

**Comment by lukefromdc** [comment]
Mate-common installed with meson does work now, just no docs installed.
Note that I will NOT be home tomorrow, possibly delaying this a bit

**Comment by lukefromdc** [comment]
On uninstall I got this list of removed files:
```

[0/1] /usr/bin/meson --internal uninstall
Deleted: /usr/share/aclocal/mate-code-coverage.m4
Deleted: /usr/share/aclocal/mate-common.m4
Deleted: /usr/share/aclocal/mate-compiler-flags.m4
Deleted: /usr/bin/mate-autogen
Deleted: /usr/share/man/man1/mate-autogen.1
Deleted: /usr/share/man/man1/mate-doc-common.1
Deleted: /usr/share/mate-common/data/omf.make
Deleted: /usr/share/mate-common/data/xmldocs.make
Deleted: /usr/bin/mate-doc-common
Deleted: /usr/share/mate-common/data
Deleted: /usr/share/mate-common

```

**Comment by zhuyaliang** [comment]
@lukefromdc 
I refer to the ```makefile``` rules to create ```meson.build```
```
make install DESTDIR=/tmp/common-make
DESTDIR=/tmp/common-meson ninja -C build/ install

[test@localhost mate-common]$ find /tmp/common-make/
/tmp/common-make/
/tmp/common-make/usr
/tmp/common-make/usr/bin
/tmp/common-make/usr/bin/mate-autogen
/tmp/common-make/usr/bin/mate-doc-common
/tmp/common-make/usr/share
/tmp/common-make/usr/share/man
/tmp/common-make/usr/share/man/man1
/tmp/common-make/usr/share/man/man1/mate-doc-common.1
/tmp/common-make/usr/share/man/man1/mate-autogen.1
/tmp/common-make/usr/share/aclocal
/tmp/common-make/usr/share/aclocal/mate-common.m4
/tmp/common-make/usr/share/aclocal/mate-code-coverage.m4
/tmp/common-make/usr/share/aclocal/mate-compiler-flags.m4
/tmp/common-make/usr/share/mate-common
/tmp/common-make/usr/share/mate-common/data
/tmp/common-make/usr/share/mate-common/data/xmldocs.make
/tmp/common-make/usr/share/mate-common/data/omf.make

[test@localhost mate-common]$ find /tmp/common-meson/
/tmp/common-meson/
/tmp/common-meson/usr
/tmp/common-meson/usr/bin
/tmp/common-meson/usr/bin/mate-autogen
/tmp/common-meson/usr/bin/mate-doc-common
/tmp/common-meson/usr/share
/tmp/common-meson/usr/share/man
/tmp/common-meson/usr/share/man/man1
/tmp/common-meson/usr/share/man/man1/mate-doc-common.1
/tmp/common-meson/usr/share/man/man1/mate-autogen.1
/tmp/common-meson/usr/share/aclocal
/tmp/common-meson/usr/share/aclocal/mate-common.m4
/tmp/common-meson/usr/share/aclocal/mate-code-coverage.m4
/tmp/common-meson/usr/share/aclocal/mate-compiler-flags.m4
/tmp/common-meson/usr/share/mate-common
/tmp/common-meson/usr/share/mate-common/data
/tmp/common-meson/usr/share/mate-common/data/xmldocs.make
/tmp/common-meson/usr/share/mate-common/data/omf.make
[test@localhost mate-common]$ 
```

``/usr/share/docs/mate-common``` added by ```debian```  maintainer

[debian](https://sources.debian.org/src/mate-common/1.26.0-1/debian/)

**Comment by lukefromdc** [comment]
Sorry, in my autotools builds done WITHOUT any patches from Debian, /usr/share/doc/mate-common is always installed, and I do NOT have to manually drop it into the Debs I build with Checkinstall. My MATE install is built entirely from git master or PR packages with no distro patches anywhere.

I won't merge this without either this being fixed or a vote for it from another maintainer as I am opposed to changing this default.
mate-common

**Comment by zhuyaliang** [comment]
@lukefromdc Do not view the file list from the installation package,Please use ```autogen.sh``` && ```make``` && ```make install```

**Comment by zhuyaliang** [comment]
The  ```Archlinux``` ```Fedora``` ```Debian```  mate-common package provides different files, so referencing the installation package is meaningless

**Comment by lukefromdc** [comment]
I just found something interesting: Checkinstall provides an option to install the files in /usr/share/doc-and in fact they do NOT get installed by `make install` so you have in fact matched the behavior of autotools. Will merge. 

What I had never noticed was that on some packages `make install` does not install them. I have hand packed my custom changelogs into /usr/share/doc copied from previous packages so long I never noticed until now that I was not having to overwrite or add to a default set of docs files. Probably none of the mate packages I have would have included them by default

Pardon the hassle

**Pull request merged**
