### PR TITLE
update MATE_CXX_WARNINGS macro

### PR DESCRIPTION
**Pull request by rbuj**
- add more compiler flags
- remove this constraint: "Only use compiler warnings for gcc"
- remove the ansi flag (c++98 iso standard)
- Use autoconf archive macros (AX_)

### CODE REVIEW

**Comment by raveit65** [comment]
common, why did you didn't say that you want to edit more?
I did ask you yesterday here https://github.com/mate-desktop/mate-common/pull/29#issuecomment-536051684
I just released 1.23.2

**Comment by rbuj** [comment]
@raveit65 I didn't know that I will edit it more. I edited it when I reviewed mate-system-monitor today.

**Comment by raveit65** [comment]
@rbuj 
Ok, do you have more plans to edit mate-common or can i make a new release when this PR is merged?

**Comment by rbuj** [comment]
I'm reviewing this PR, I got unexpected results with mate-system-monitor...

**Comment by rbuj** [comment]
@raveit65 I'm sorry for the inconvenience, you can make a new release after merging this.

**Pull request merged**
