### PR TITLE
update mate-compiler-flags macro

### PR DESCRIPTION
**Pull request by raveit65**
This macro is used if a package use `MATE_COMPILE_WARNINGS` in configure.ac.
`--enable-compile-warnings=[no/minimum/yes/maximum/error]`
maximum use now more warnings which we used in latest PRs of some packages.

Maybe some of the new CFLAGS_WARNS can be moved to --enable-compile-warnings=yes ?
Suggestions are welcome.

### CODE REVIEW

**Comment by rbuj** [comment]
clang understands most gcc flags, for that reason I recommend to remove this constraint: "Only use compiler warnings for gcc"
https://github.com/mate-desktop/mate-common/blob/f7618d169e78cd76d88fc9999277bcb0bc1fc353/macros/mate-compiler-flags.m4#L32-L34
and check whether the compiler flag is supported like code below, which is more stable and convenient:
https://github.com/mate-desktop/mate-common/blob/f7618d169e78cd76d88fc9999277bcb0bc1fc353/macros/mate-compiler-flags.m4#L52-L66
I agree with all new flags, I think we should discuss about removing the ansi flag (c89 iso standard) since we use c99 standard in most MATE code.
https://github.com/mate-desktop/mate-common/blob/f7618d169e78cd76d88fc9999277bcb0bc1fc353/macros/mate-compiler-flags.m4#L87-L98

**Comment by raveit65** [comment]
PR is updated.

> and check whether the compiler flag is supported like code below, which is more stable and convenient:

I don't understand what i should do here?

**Comment by rbuj** [comment]
Using autoconf archive macros (AX_):
```m4
# MATE_COMPILE_WARNINGS
# Turn on many useful compiler warnings
# For now, only works on GCC
#
#   Copyright (C) 2011 Perberos <perberos@gmail.com>
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.


AC_DEFUN([MATE_COMPILE_WARNINGS],[
    dnl ******************************
    dnl More compiler warnings
    dnl ******************************

    AC_ARG_ENABLE(compile-warnings,
                  AS_HELP_STRING([--enable-compile-warnings=@<:@no/minimum/yes/maximum/error@:>@],
                                 [Turn on compiler warnings]),,
                  [enable_compile_warnings="m4_default([$1],[yes])"])

    AC_LANG_PUSH([C])

    case "$enable_compile_warnings" in
    no)
	warning_flags=
	;;
    minimum)
	warning_flags="-Wall"
	;;
    yes)
	warning_flags="-Wall -Wmissing-prototypes"
	;;
    maximum|error)
	warning_flags="-Wall -Wmissing-prototypes -Wbad-function-cast -Wcast-align -Wextra -Wformat-nonliteral -Wmissing-declarations -Wmissing-field-initializers -Wnested-externs -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-prototypes -Werror=format-security -Wno-sign-compare"
	if test "$enable_compile_warnings" = "error" ; then
	    warning_flags="$warning_flags -Werror"
	fi
	;;
    *)
	AC_MSG_ERROR(Unknown argument '$enable_compile_warnings' to --enable-compile-warnings)
	;;
    esac

    # Always pass -Werror=unknown-warning-option to get Clang to fail on bad
    # flags, otherwise they are always appended to the warn_cflags variable, and
    # Clang warns on them for every compilation unit.
    # If this is passed to GCC, it will explode, so the flag must be enabled
    # conditionally.
    AX_CHECK_COMPILE_FLAG([-Werror=unknown-warning-option],[
        compiler_flags_test="-Werror=unknown-warning-option"
    ],[
        compiler_flags_test=""
    ])

    for flag in $warning_flags; do
         AX_CHECK_COMPILE_FLAG([$flag], [AX_APPEND_FLAG([$flag], [WARN_CFLAGS])], [], [$compiler_flags_test], [])
    done

    AC_MSG_CHECKING(flags to pass to the C compiler $CC)
    AC_MSG_RESULT(${WARN_CFLAGS})

    AC_LANG_POP([C])
    AC_SUBST(WARN_CFLAGS)
])

dnl For C++, do basically the same thing.

AC_DEFUN([MATE_CXX_WARNINGS],[
  AC_ARG_ENABLE(cxx-warnings,
                AS_HELP_STRING([--enable-cxx-warnings=@<:@no/minimum/yes@:>@]
                               [Turn on compiler warnings.]),,
                [enable_cxx_warnings="m4_default([$1],[minimum])"])

  AC_MSG_CHECKING(what warning flags to pass to the C++ compiler)
  warnCXXFLAGS=
  if test "x$GXX" != xyes; then
    enable_cxx_warnings=no
  fi
  if test "x$enable_cxx_warnings" != "xno"; then
    if test "x$GXX" = "xyes"; then
      case " $CXXFLAGS " in
      *[\ \	]-Wall[\ \	]*) ;;
      *) warnCXXFLAGS="-Wall -Wno-unused" ;;
      esac

      ## -W is not all that useful.  And it cannot be controlled
      ## with individual -Wno-xxx flags, unlike -Wall
      if test "x$enable_cxx_warnings" = "xyes"; then
	warnCXXFLAGS="$warnCXXFLAGS -Wshadow -Woverloaded-virtual"
      fi
    fi
  fi
  AC_MSG_RESULT($warnCXXFLAGS)

   AC_ARG_ENABLE(iso-cxx,
                 AS_HELP_STRING([--enable-iso-cxx],
                                [Try to warn if code is not ISO C++ ]),,
                 [enable_iso_cxx=no])

   AC_MSG_CHECKING(what language compliance flags to pass to the C++ compiler)
   complCXXFLAGS=
   if test "x$enable_iso_cxx" != "xno"; then
     if test "x$GXX" = "xyes"; then
      case " $CXXFLAGS " in
      *[\ \	]-ansi[\ \	]*) ;;
      *) complCXXFLAGS="$complCXXFLAGS -ansi" ;;
      esac

      case " $CXXFLAGS " in
      *[\ \	]-pedantic[\ \	]*) ;;
      *) complCXXFLAGS="$complCXXFLAGS -pedantic" ;;
      esac
     fi
   fi
  AC_MSG_RESULT($complCXXFLAGS)

  WARN_CXXFLAGS="$CXXFLAGS $warnCXXFLAGS $complCXXFLAGS"
  AC_SUBST(WARN_CXXFLAGS)
])
```
Test engrampa:
```diff
diff --git a/configure.ac b/configure.ac
index c2e6238..6600379 100644
--- a/configure.ac
+++ b/configure.ac
@@ -11,6 +11,7 @@ AC_CONFIG_HEADER([config.h])
 AC_CONFIG_MACRO_DIR([m4])
 
 MATE_COMMON_INIT
+MATE_COMPILE_WARNINGS
 
 AC_PROG_CC
 AM_DISABLE_STATIC
@@ -48,26 +49,6 @@ AC_SUBST([GTK_LIBS])
 
 dnl ===========================================================================
 
-WARN_CFLAGS="-Wall -Wcast-align -Wtype-limits -Wclobbered -Wempty-body -Wignored-qualifiers"
-
-for option in $WARN_CFLAGS; do
-       SAVE_CFLAGS="$CFLAGS"
-       CFLAGS="$CFLAGS $option"
-       AC_MSG_CHECKING([whether gcc understands $option])
-       AC_COMPILE_IFELSE([AC_LANG_PROGRAM([[]], [[]])],[has_option=yes],[has_option=no])
-       if test x$has_option = xyes; then
-               WARNINGS="$WARNINGS $option"
-       fi
-       AC_MSG_RESULT($has_option)
-       CFLAGS="$SAVE_CFLAGS"
-       unset has_option
-       unset SAVE_CFLAGS
-done
-unset option
-CFLAGS="$CFLAGS $WARNINGS"
-
-dnl ===========================================================================
-
 AC_ARG_ENABLE(run_in_place,
               AS_HELP_STRING([--enable-run-in-place],
                              [load ui data and extensions from the source tree]),,
```
configure:
```
$ ./autogen.sh --enable-compile-warnings=yes
```
output:
```shell
$ grep WARN_CFLAGS Makefile
WARN_CFLAGS = -Wall -Wmissing-prototypes
```

**Comment by raveit65** [comment]
Thanks , i followed your advice and PR is updated.

**Comment by raveit65** [comment]
I think i will cherry-pick that to 1.22 and make a new release, otherwise we won't see that in travis builds.

**Comment by raveit65** [comment]
@rbuj 
Can you leave karma for f31 and f30 please?
https://bodhi.fedoraproject.org/updates/FEDORA-2019-222d346e40
https://bodhi.fedoraproject.org/updates/FEDORA-2019-b2ee026fc2

**Comment by raveit65** [comment]
@rbuj 
Huston we have a problem.
I can't build mate-utils (master) against released mate-common-1.22.1-1.fc30 any more with mock build server.
```
checking how to hardcode library paths into programs... immediate
checking for glib-genmarshal... /usr/bin/glib-genmarshal
checking for glib-mkenums... /usr/bin/glib-mkenums
checking for rsvg-convert... no
checking for inkscape... no
./configure: line 12565: syntax error near unexpected token `-Werror=unknown-warning-option,'
./configure: line 12565: `    AX_CHECK_COMPILE_FLAG(-Werror=unknown-warning-option,'


RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.KdCvan (%build)
    Bad exit status from /var/tmp/rpm-tmp.KdCvan (%build)
DEBUG: Child return code was: 1
INFO: EXCEPTION: [Error()]
```
mate-utils use `MATE_COMPILE_WARNINGS([yes])` in configure.ac.
Can you please take a look at it?
mate-common-1.22.1-1.fc30 was pushed to fedora stable, in result we will get a problem with fedora travis ci builds.

**Comment by raveit65** [comment]
Ok, using BuildRequires:  autoconf-archive fixes the problem.
Hmm, i need to add that to mate-common as run time dependency in fedora to fix building.
But i am not sure how to fix that for other distros.
I think we need to add this to every package which use MATE_COMPILE_WARNINGS.
@mate-desktop/core-team 
Thoughts?

**Comment by rbuj** [comment]
The Makefile.am files must also be modified, since warning flags are stored in WARN_FLAGS variable for now. Example: https://github.com/mate-desktop/engrampa/pull/327

**Comment by raveit65** [comment]
And we need to do this for 1.22 too which packages were fresh released, damned.
Well, i have update fedora f30/31, so travis-ci fedora builds should work again in some hours.
https://bodhi.fedoraproject.org/users/raveit65

**Pull request merged**
