### PR TITLE
travis: update to f30 and ubunt-19.10

### PR DESCRIPTION
**Pull request by raveit65**

### CODE REVIEW

**Comment by raveit65** [comment]
@yetist 
Do you think it is possible to disable updating release page for fedora rawhide?
To avoid to do the same as with f30 with travis-CI
In general i'd like to add fedora rawhide to master branch for all repos.

**Comment by yetist** [comment]
On the master branch, using fedora:rawhide and debian:unstable is of course ideal, but according to my tests, this makes us feel sad.
Because fedora:rawhide and debian:unstable are very unstable, they usually fail when run `yum/apt install`,  and the PR fails on travis next.

**Comment by raveit65** [comment]
Well, of course building on fedora rawhide can fail because it is rawhide.
But when checks for rawhide build failed in PR than we have to check why this happens and it can be ignored when it fails and build for f30 runs fine. immo.
For this reason i'd like to build for rawhide and f30.
My concern was more about double action for gh-pages and release-page.
Fedora rawhide is very useful to see very early code changes in linux world and sooner or later this will be land in all other distros.
Maybe we can test how often a travis build for fedora rawhide will fail in another repo with more activity?
@mate-desktop/core-team 
Thoughts?

PS: in the end i don't care much about, because is see early software changes in linux world always at fedora build server for rawhide.

**Comment by yetist** [comment]
I don't care, if use rawhide can help you, you can do this.

**Comment by raveit65** [comment]
Ok, i dropped rawhide from config.

**Pull request merged**
