### PR TITLE
switch from APPDATA_XML to APPSTREAM_XML

### LINKED ISSUE #22: Please switch from APPDATA_XML to APPSTREAM_XML
appstream-glib 0.7 (currently in Ubuntu 17.10 Alpha) dropped the `APPDATA_XML` macro. It's been deprecated for a few years. Please use `APPSTREAM_XML` instead in `macros/mate-autogen`

The dropping of that macro might have been a mistake but you might as well fix this now anyway. See https://github.com/hughsie/appstream-glib/issues/183

### PR DESCRIPTION
**Pull request by info-cppsp**
fix #22 

came across this. I'm not sure how to test it, so please help...

### CODE REVIEW

**Comment by raveit65** [comment]
All this stuff is for gnome-software  application.
You can test it with it.

**Comment by raveit65** [comment]
Eom use such a file.
https://github.com/mate-desktop/eom/blob/master/data/eom.appdata.xml.in

**Comment by info-cppsp** [comment]
ok, I'll make a project out of this as there are more repos with appdata files...

**Comment by raveit65** [comment]
> ok, I'll make a project out of this as there are more repos with appdata files...
> -> wrote it up into project 1

Good idea, thank you.

**Comment by monsta** [comment]
Looks like none of our projects has `APPDATA_XML` or `APPSTREAM_XML` in `configure.ac` (that's what `mate-autogen` checks), so this PR doesn't really affect anything...

**Pull request closed without merging**
